### ISSUE TITLE
LYNX isn't installed!  Can't use this tool without it...

### ISSUE THREAD

**Issue by cacaocaca** [Hood3dRob1n/BinGoo#2]
Linux kali 4.7.0-kali1-686-pae #1 SMP Debian 4.7.8-1kali1 (2016-10-24) i686 GNU/Linux
So is some month i dont  try more this script first working good .. Now i try to do 
root@kali:~/Scrivania/BinGoo# ./bingoo 

          __   _,--="=--,_   __
         /  \."    .-.    "./  \
        /  ,/  _   : :   _  \/` \
        \  `| /o\  :_:  /o\ |\__/
         `-'| :="~` _ `~"=: |
            \`     (_)     `/
     .-"-.   \      |      /   .-"-.
.---{     }--|  /,.-'-.,\  |--{     }---.
 )  (_)_)_)  \_/`~-===-~`\_/  (_(_(_)  (
(   ____  _        ____             _   )
 ) | __ )(_)_ __  / ___| ___   ___ | | (
(  |  _ \| | '_ \| |  _ / _ \ / _ \| |  )
 ) | |_) | | | | | |_| | (_) | (_) |_| (
(  |____/|_|_| |_|\____|\___/ \___/(_)  )
 )                                     (
'---------------------By-Hood3dRob1n----'
LYNX isn't installed!  Can't use this tool without it...
root@kali:~/Scrivania/BinGoo# 
I need to install something ?

**Comment by Hood3dRob1n** [comment]
Lynx apparently doesn't come installed by default anymore on Kali and it's a really old script...

Listen to the error and install Lynx to resolve things:
apt-get install lynx lynx-common

**Comment by cacaocaca** [comment]
Thanks work ;)
