### ISSUE TITLE
How To Apply Sql????

### ISSUE THREAD

**Issue by Kilua17Gamer** [Hood3dRob1n/BinGoo#3]
Pls Help Me ,I Didnt Understand :) on phone using GNURoot Debian thanks

**Comment by Hood3dRob1n** [comment]
Leave an actual question and I'll try to help...

**Comment by Kilua17Gamer** [comment]
On Sunday, December 18, 2016, Hood3dRob1n <notifications@github.com> wrote:
> Closed #3.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



I mean hoodedrobin -_- im using your tools on android so pls help if im
change the location it will say syntax error and will not work so bad
Once again thanks
